### ISSUE TITLE
Example use of get_transactions returns 400 error

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/explorer-api#1]
On https://app.swaggerhub.com/apis/devintegral7/fantom-explorer_api/0.1#/transaction/get_api_v1_get_transactions, the example returns a 400 error:

<img width="559" alt="Screen Shot 2019-12-09 at 10 41 00 pm" src="https://user-images.githubusercontent.com/5106444/70433213-3c491480-1ad5-11ea-934e-1f7403760367.png">

<img width="1436" alt="Screen Shot 2019-12-09 at 10 40 46 pm" src="https://user-images.githubusercontent.com/5106444/70433217-41a65f00-1ad5-11ea-873e-cec02731d2a2.png">

**Comment by devintegral7** [comment]
Clarified: example address was taken from different test-net.
