### ISSUE TITLE
Some validators display no delegators at api level

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/explorer-api#5]
Some validators have addresses delegated to them, but these addresses do no appear in the delegates tab. 

e.g http://api.fantom.network/api/v1/staker/id/21?verbosity=2 shows "delegatedMe": 13270274000000000000000000.

But http://api.fantom.network/api/v1/delegator/staker/21?verbosity=2 returns "Not Found" i.e no delegators found.

http://explorer.fantom.network/validator/21

**Comment by devintegral7** [comment]
@MKong
